<a href="https://colab.research.google.com/github/seojun779/web_2026_bigdatacomputing/blob/main/class_wed_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. 넘파일 다차원 배열(ndarray) 객체 생성
- import numpy as np
- 리스트을 이용하여 다차원 배열 생성
- np.array(리스트)
  - 리스트 → 배열로 바꾸고 싶을 때
  - 단순 저장 → 수학 연산이 필요할 때
  - 데이터 분석/머신러닝 모델에 데이터를 입력할 때
- 속성 :
  - ndim : 배열 축 혹은 차원의 개수
  - shape : 배열의 형상을 (n, m) 형식의 튜플형으로 표시
  - size :
    - 배열 원소의 개수
    - (m,n) 형상 배열의 size = m*n
  - dtype : 배열 원소의 자료형을 기술
  - astype : 배열 원소 형 변환

In [ ]:
# 1. 리스트를 이용하여 1차원 배열 생성

import numpy as np
data = [10, 20, 30]
print(data)
print("="*100)
arr = np.array(data) # 1차원 배열 반환
print(arr)
print(type(arr))
print(arr.ndim) # 1
print(arr.shape) # (3,)
print(arr.size) # 3
print(arr. dtype) # int64

[10, 20, 30]
[10 20 30]
<class 'numpy.ndarray'>
1
(3,)
3
int64


In [ ]:
# 2. 중첩리스트를 이용하여 2차원 배열 생성
# 머신러닝에서 행은 샘플의 개수, 열은 각 샘플이 지니고 있는 특징의 개수를 표현
import numpy as np

# 2행 3열 구조로 2명의 학생에 대한 3과목의 점수를 기록 -> 넘파이 2차원 배열로 생성
data = [[90, 80, 100],[70, 90, 90]]
print(data)
print("="*100)
arr_2d = np.array(data, dtype="float64") # 2d arrary
print(arr_2d)
print(type(arr_2d))
print(arr_2d.ndim) # 2
print(arr_2d.shape) # (2, 3)
print(arr_2d.size) # 6
print(arr_2d.dtype) # float64

[[90, 80, 100], [70, 90, 90]]
[[ 90.  80. 100.]
 [ 70.  90.  90.]]
<class 'numpy.ndarray'>
2
(2, 3)
6
float64


In [ ]:
# 3. 3차원 넘파이 배열을 이용해서 이미지 데이터 기록
# 3차원 배열은 (axis0, axis1, axis2) = (깊이, 높이, 너비)
# 디지털 이미지 데이터 (가로, 세로, RGB 채널)
# 2*2 크기의 아주 작은 컬러 이미지 하나

import numpy as np
tensor_list = [
    [[255,0,0], [0,255,0]],
    [[0,0,255], [255,255,0]]
]
tensor = np.array(tensor_list)
print(tensor.ndim) # 3
print(tensor.shape) # (2,2,3)
print(tensor.size) # 12

3
(2, 2, 3)
12
int64


# 2. 넘파이 다차원 배열 간 사칙 연산
  - 피연산자 다차원 배열들의 형상이 같다는 가정
  - +, -, *, / 연산 수행
  - 배열 프로그래밍
  - 선형대수의 벡터화 연산
  - 벡터을 병렬 연산 수행
    - 데이터 병렬 처리

In [ ]:
# 1차원 배열 사칙연산 -> 1차원 배열 결과로 반환
# 1차원 넘파이 배열 생성
store_a = [1000, 2000, 1500]
store_b = [2000, 1000, 1000]
arr_a = np.array(store_a)
arr_b = np.array(store_b)
# 형태가 같은 1차원 배열 간 연산 : (3,)
print(arr_a + arr_b) # [3000 3000 2500]
print(arr_a * arr_b)
print(arr_a - arr_b)
print(arr_a / arr_b)

[3000 3000 2500]
[2000000 2000000 1500000]
[-1000  1000   500]
[0.5 2.  1.5]


In [ ]:
# 2차원 배열 사칙연산 : 동일한 형태를 가지는 배열 (2,3)
arr1_2d = np.array([[1,2,3], [4,5,6]])
arr2_2d = np.array([[10,20,30], [40,50,60]])

# 사칙 연산
print(arr1_2d + arr2_2d)
print(arr1_2d * arr2_2d)
print(arr1_2d - arr2_2d)
print(arr1_2d / arr2_2d)

[[11 22 33]
 [44 55 66]]
[[ 10  40  90]
 [160 250 360]]
[[ -9 -18 -27]
 [-36 -45 -54]]
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]]


# 3. 넘파이 다차원 배열과 브로드캐스팅
- 형상이 다른 두 배열 간 사칙연산 수행
  - 스칼라
    - 다차원 배열 * 스칼라, 다차원 배열 + 스칼라, 다차원 배열 - 스칼라, 다차원 배열 / 스칼라
    - 스칼라 + 배열, 스칼라 - 배열, 스칼라 * 배열, 스칼라 /배열

  - 형상이 다른 배열과 사칙 연산

- 브로드캐스팅 이용해서 다차원 배열 프로그래밍
  - 배열의 차원에 맞게 벡터로 확장하여 동일하게 만듦
  - 벡터화 연산 * 병렬 처리

In [ ]:
# 형상이 서로 다른 배열과 스칼라 간 사칙연산
import numpy as np
arr_1d = np.array([1,2,3]) # (3,)
print(arr_1d + 10)
print(arr_1d - 10)
print(arr_1d * 10)
print(arr_1d / 10)

print("="*100)

# 2차원 배열과 1차원 배열 간 사칙연산 : (2,3), (3)
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d + arr_1d)

# 2차원 배열과 1차원 배열 간 사칙 연산 불가 : (2,4), (3)
arr_2d = np.array([[1,2,3,4],[4,5,6,7]])
#print(arr_2d + arr_1d)

#3차원 배열과 2차원 배열 간 사칙 연산 : (3,2,4), (2,4)
arr_3d = np.array([[[1,2,3,4], [5,6,7,8]], [[9,10,11,12], [13,14,15,16]], [[17,18,19,20], [21,22,23,24]]])
print(arr_3d.shape)
print(arr_2d + arr_3d)
print(arr_2d - arr_3d)

[11 12 13]
[-9 -8 -7]
[10 20 30]
[0.1 0.2 0.3]
[[2 4 6]
 [5 7 9]]
(3, 2, 4)
[[[ 2  4  6  8]
  [ 9 11 13 15]]

 [[10 12 14 16]
  [17 19 21 23]]

 [[18 20 22 24]
  [25 27 29 31]]]
[[[  0   0   0   0]
  [ -1  -1  -1  -1]]

 [[ -8  -8  -8  -8]
  [ -9  -9  -9  -9]]

 [[-16 -16 -16 -16]
  [-17 -17 -17 -17]]]


# 4. 라이브러를 이용하여 연속적인 값을 가지는 다차원 배열 생성

- zeros(n, m)
- ones(n,m)
- arange(start, stop, step)
- linspace(start,stop, num)
- logspace(start, stop, num)


In [ ]:
# 특정 패턴을 가진 넘파이 배열 생성
# 1. (2,3,4) 구조로 배열 원소가 모두 0인 넘파일 배열

import numpy as np
zeros = np.zeros((2,3,4))
print(zeros)
print(zeros.shape, zeros.ndim, zeros.size, zeros.dtype)
print("="*100)

# 2. 0~ 10사이의 정수를 가진 1차원 배열을 생성 -> 2차원 배열로 변환 (2,5)
arr_1d = np.arange(0, 10, 1)
print(arr_1d)
print(arr_1d.shape, arr_1d.size, arr_1d.ndim, arr_1d.dtype)
arr_2d = arr_1d.reshape(2,5)
print(arr_2d)
print("="*100)

# 2-1 2차원 배열 (2, 4)
#arr_2d = arr_1d.reshape(2,4) -> 오류 발생 -> 해결방법 reshape(2,-1)
arr_2d = arr_1d.reshape(2,-1)
print(arr_2d)
print("="*100)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(2, 3, 4) 3 24 float64
[0 1 2 3 4 5 6 7 8 9]
(10,) 10 1 int64
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


# 5. 다차원 배열을 축을 이용하여 원소를 삽입하여 배열 확장하기
- np.insert(배열객체, 삽입위치, 삽입 스칼라 값, 삽입할방향)
  - 1차원 배열에 삽입
  - 다차원 배열에 삽입
    - 주어진 배열의 형상을 고려하여 브로드캐스팅 방식



In [ ]:
# insert() 필요성 : 누락된 데이터 포인트를 보관 또는 머신러닝 데이터셋의 특정 열에 새로운 feature(ID, 바이어스)을 삽입

import numpy as np
arr_1d = np.array([10,30,40,50]) # 1d 배열 -> 20 누락
# 인덱스 1 위치에 숫자20을 삽입
corrected_data = np.insert(arr_1d,1,20)
print("보정전 :", arr_1d)
print("보정후 :", corrected_data)
print("="*100)

# 2차원 배열에서 열 위치에서 삽입
matrix = np.zeros((2,3))
# 1번 열 위치에 [5,5] 삽입
new_matrix = np.insert(matrix, 1, 5, axis = 1)
print("보정전 :", matrix)
print("보정후 :", new_matrix)
print("="*100)

보정전 : [10 30 40 50]
보정후 : [10 20 30 40 50]
보정전 : [[0. 0. 0.]
 [0. 0. 0.]]
보정후 : [[0. 5. 0. 0.]
 [0. 5. 0. 0.]]


# 6. 다차원 배열의 지정된 축 방향으로 원소들을 뒤집기
  - np.flip(배열객체, axis=)

# 7. 넘파이 다차원 배열의 인덱싱
- 다차원 배열의 특정 원소 추출 방식
- 인덱스 정수을 이용
- 인덱싱은 두 축을 이용해서 함
  - axis 0 ; 행 참조
  - axis 1 ; 열 참조
- arr[][]
- arr[,]
- arr[]


# 8. 넘파이 다차원 배열의 인덱싱을 이용한 슬라이싱
- 다차원 배열에서 작은 배열을 추출
- 인덱싱을 이용하여 슬라이싱 범위 지정
- 두 축을 이용해서 특정한 행과 열만 별도로 적용하여 추출함
  - axis 0 ,  axis 1
  - arr[] ; axis 0 사용
  - arr[:, :] ;  두 개의 축을 동시에 사용할 때는 쉼표로 구분
  - arr[: :step] ; axis 0을 이용하여 간격을 두고 추출
  - arr[::step, ::step]; 두 개의 축을 이용하여 간격을 두고 추출


# 9.  넘파이 다차원 배열의 슬라이싱을 이용한 논리인덱싱
- 특정한 조건을 만족하는 배열의 원소값만을 추출하여 1차원 배열 객체로 반환
- 브로드캐스팅하여 병렬 연산 처리


1. 주어진 배열을 이용하여 조건식을 만족하는 동일한 형상을 가지는 불리언 배열을 생성

2.   주어진 배열에 불리언 배열을 인덱스로 지정






# 10. 넘파이의 강력한 기능
- 다차원 배열의 최대값, 최소값, 평균값 : 벡터화 연산을 이용한 Reduction 기능
  - arr.max()
  - arr.min(0
  - arr.mean()
- 다차원 배열의 평탄화 기능
  - arr.flatten()
- 다차원 배열의 원소의 자료형 변환
  - arr.astype(np.int64)
  - arr.astype(np.float64)

- 2차원 배열의 행과 열의 순서 바꾸기
  -arr.T

- 다차원 배열의 오름차순 정렬
  - arr.sort()
  - arr.sort(axis=0)



# 11. 다차원 배열 생성 ; 기존 배열의 차원과 형태 변환하여 생성
- 일반적으로 1차원 배열을 생성하여 다차원 배열로 변환
  - np.arange(start, stop, step)

- 배열의 원소 총개수는 유지
- np.reshape(튜플형태로 형상 표시)
  - arr.reshape(n,)
  - arr.reshape(n,m)
  - arr.reshape(n, -1)
  - arr.reshape(n,m,l)
- np.flatten()
  - 고차원 배열 -> 1차원 배열 변환

# 13.난수을 이용한 다차원 배열 만들기
- random 모듈
  - rand(개수) - 0과 1사이의 균등분포의 난수 표본을 추출
  - randn(개수) - 표준정규분포의 난수 표본 추출
  - randint(최소값,최대값,개수)- 주어진 범위내의 정수 난수 생성. 최대값은 미포함
  - normal(평균, 표준편차, 개수) - 정규분포의 난수 표본 추출
  - uniform(개수) - 균등분포에서 표본 추출
  - shuffle() - 배열를 임의의 순서로 섞는다
  - permutation() - 배열을 임의의 순서로 섞음


# 14. 다차원 배열 프로그래밍
- 벡터화 연산 (데이터병렬 처리)
  - 배열 간 연산
  - 리덕션
    - np.sum(arr, axis=)
    - np.mean(arr, axis=)
    - arr.sum(axis=0)
    - arr.sum(axis=1)
    - arr.sum(axis=(0,1))
  - 조건 리덕션 원리 (Boolean to Integer)
      - NumPy에서 리덕션이 강력한 이유는 **논리값(True/False)**을 연산하는 순간 **숫자(1/0)**로 자동 변환.

      - np.sum(condition) : 조건이 참(True)인 개수를 구함

      - np.mean(condition) : 조건이 참(True)인 비율을 구함 (예: 0.7이면 70%가 참)
      - 이 리덕션 기법들을 활용해서 실제 데이터셋에서 "이상치(Outlier)"를 찾기

# 15. 넘파일 배열의 결합
- np.concatenate(튜플)
- np.vstack(튜플 또는 리스트)
- np.hstack(튜플 또는 리스트)
- np.r_[ 콤마 사용하여 나열 ]
- np.c_[콤마 사용하여 나열]
- np.column_stack(리스트)


# 🛠️ 응용문제: Numpy 배열 결합 중심의 전처리 프로그램
- 1) 개별 센서 데이터 통합
- 2) 레이블링
- 3) 훈련 데이터셋 구성의 3단계로 구성

-  핵심 결합 함수
  - np.concatenate((a, b), axis=0):
  - np.vstack((a, b)):
  - np.column_stack((X, y)):
    - 1차원 레이블 배열을 2차원 데이터셋의 새로운 **열(Column)**로 붙인다.
    - 자동으로 y를 2차원으로 해석.
    - np.zeros()
    - np.ones()